import { ImageResponse } from "next/og";

// ============================================
// OpenGraph image for social sharing
// ============================================
// Next.js automatically generates a PNG from this file at build time and
// references it as the og:image for every page in this route segment.
// Specifically: when users share https://luxdriveksa.com on WhatsApp,
// Slack, Discord, Twitter/X, LinkedIn, iMessage, Facebook, etc., this is
// the image that appears in the link preview card.
//
// Recommended size: 1200x630 (1.91:1) — works across all major platforms.
// Files generated by this route are served from /opengraph-image at build time.
// ============================================

export const alt = "LuxDrive — Premium Chauffeur Services in Saudi Arabia";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OpenGraphImage() {
  return new ImageResponse(
    <div
      style={{
        height: "100%",
        width: "100%",
        background: "#0a0a0a",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
      }}
    >
      {/* Subtle gold frame — luxury editorial signature */}
      <div
        style={{
          position: "absolute",
          top: 30,
          left: 30,
          right: 30,
          bottom: 30,
          border: "1px solid rgba(201, 169, 97, 0.3)",
          display: "flex",
        }}
      />

      {/* Corner brackets (top-left) */}
      <div
        style={{
          position: "absolute",
          top: 34,
          left: 34,
          width: 24,
          height: 1,
          background: "#C9A961",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          top: 34,
          left: 34,
          width: 1,
          height: 24,
          background: "#C9A961",
          display: "flex",
        }}
      />
      {/* Corner brackets (top-right) */}
      <div
        style={{
          position: "absolute",
          top: 34,
          right: 34,
          width: 24,
          height: 1,
          background: "#C9A961",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          top: 34,
          right: 34,
          width: 1,
          height: 24,
          background: "#C9A961",
          display: "flex",
        }}
      />
      {/* Corner brackets (bottom-left) */}
      <div
        style={{
          position: "absolute",
          bottom: 34,
          left: 34,
          width: 24,
          height: 1,
          background: "#C9A961",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          bottom: 34,
          left: 34,
          width: 1,
          height: 24,
          background: "#C9A961",
          display: "flex",
        }}
      />
      {/* Corner brackets (bottom-right) */}
      <div
        style={{
          position: "absolute",
          bottom: 34,
          right: 34,
          width: 24,
          height: 1,
          background: "#C9A961",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          bottom: 34,
          right: 34,
          width: 1,
          height: 24,
          background: "#C9A961",
          display: "flex",
        }}
      />

      {/* Arabic name لكسدرايف */}
      <div
        style={{
          fontSize: 48,
          color: "#C9A961",
          marginBottom: 30,
          letterSpacing: 4,
          display: "flex",
        }}
      >
        لكسدرايف
      </div>

      {/* Divider with center dot */}
      <div style={{ display: "flex", alignItems: "center", marginBottom: 50 }}>
        <div
          style={{
            width: 80,
            height: 1,
            background: "rgba(201, 169, 97, 0.6)",
            display: "flex",
          }}
        />
        <div
          style={{
            width: 6,
            height: 6,
            borderRadius: "50%",
            background: "#C9A961",
            margin: "0 12px",
            display: "flex",
          }}
        />
        <div
          style={{
            width: 80,
            height: 1,
            background: "rgba(201, 169, 97, 0.6)",
            display: "flex",
          }}
        />
      </div>

      {/* LUXDRIVE wordmark - LUX cream, DRIVE gold */}
      <div
        style={{
          fontSize: 144,
          fontWeight: 800,
          letterSpacing: 10,
          display: "flex",
          lineHeight: 1,
        }}
      >
        <span style={{ color: "#f8f5ee" }}>LUX</span>
        <span style={{ color: "#C9A961" }}>DRIVE</span>
      </div>

      {/* Gold divider with ornament */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          marginTop: 40,
          marginBottom: 30,
        }}
      >
        <div
          style={{
            width: 100,
            height: 1,
            background: "#C9A961",
            display: "flex",
          }}
        />
        <div
          style={{
            width: 8,
            height: 8,
            borderRadius: "50%",
            border: "1px solid #C9A961",
            margin: "0 16px",
            display: "flex",
          }}
        />
        <div
          style={{
            width: 100,
            height: 1,
            background: "#C9A961",
            display: "flex",
          }}
        />
      </div>

      {/* Tagline */}
      <div
        style={{
          fontSize: 42,
          color: "#C9A961",
          fontStyle: "italic",
          display: "flex",
        }}
      >
        The Art of Arrival
      </div>

      {/* Cities + Kingdom */}
      <div
        style={{
          position: "absolute",
          bottom: 70,
          fontSize: 18,
          letterSpacing: 8,
          color: "#807060",
          display: "flex",
        }}
      >
        MAKKAH · MADINAH · JEDDAH · RIYADH · KINGDOM OF SAUDI ARABIA
      </div>
    </div>,
    {
      ...size,
    },
  );
}
