"use client";

// ============================================
// apps/web/app/reset-password/page.tsx
// Public — set a new password from a reset link.
// ============================================
//
// Route: /reset-password?token=<token-from-email>
//
// The token is generated by Better Auth's forget-password flow and
// embedded in the email's link. We validate it on submit by calling
// authApi.resetPassword(newPassword, token) — Better Auth itself
// checks expiry (1 hour TTL set in lib/auth.ts) and validity.
//
// On success the user can sign in normally with their new password.

import { useState, FormEvent, Suspense } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import {
  Lock,
  Loader2,
  CheckCircle,
  AlertTriangle,
  Eye,
  EyeOff,
} from "lucide-react";
import { authApi, ApiError } from "@/lib/api";
import Logo from "@/components/shared/logo";

// Inner — wrapped in Suspense by the default export below because
// useSearchParams() crashes the Next 15+/16 production build when
// it's reached during prerender without a Suspense boundary.
function ResetPasswordPageInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get("token");

  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [done, setDone] = useState(false);

  // ===== No-token state =====
  // If the user lands on /reset-password without ?token=, the email
  // link was malformed or they navigated here manually. Show a useful
  // dead-end rather than a confusing empty form.
  if (!token) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0a0a0a] text-white p-6">
        <div className="max-w-md w-full bg-[#0f0f0f] border border-neutral-800 rounded-2xl p-8 text-center">
          <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-red-500/10 border border-red-500/30 mb-5">
            <AlertTriangle className="w-7 h-7 text-red-400" />
          </div>
          <h1 className="text-xl font-medium text-white mb-2">
            Invalid reset link
          </h1>
          <p className="text-sm text-neutral-400 mb-6 leading-relaxed">
            This page can only be reached from a password reset email. If you
            got here by mistake or the link looked broken, request a fresh reset
            email below.
          </p>
          <Link
            href="/forgot-password"
            className="inline-block w-full py-2.5 bg-[#C9A961] text-black font-medium rounded-lg hover:bg-[#C9A961]/90 transition-colors"
          >
            Request New Reset Link
          </Link>
        </div>
      </div>
    );
  }

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");

    if (password.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setSubmitting(true);
    try {
      await authApi.resetPassword(password, token);
      setDone(true);
      // Send the user back to the home page after a beat so they can
      // sign in. We auto-redirect rather than ask them to click — the
      // reset is done, no friction needed.
      setTimeout(() => {
        router.push("/");
      }, 2500);
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : "Could not reset password. The link may have expired.",
      );
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-[#0a0a0a] text-white p-6">
      <div className="w-full max-w-md">
        <div className="flex justify-center mb-8">
          <Logo size="lg" showTagline />
        </div>

        <div className="bg-[#0f0f0f] border border-neutral-800 rounded-2xl p-8">
          {!done ? (
            <>
              <h2 className="text-xl font-medium text-white mb-1">
                Set a new password
              </h2>
              <p className="text-sm text-neutral-500 mb-6">
                Choose a strong password you haven&apos;t used before.
              </p>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs text-neutral-500 mb-1.5 uppercase tracking-wide">
                    New Password
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-500" />
                    <input
                      type={showPassword ? "text" : "password"}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                      autoFocus
                      placeholder="At least 8 characters"
                      className="w-full pl-11 pr-12 py-2.5 bg-neutral-900 border border-neutral-800 rounded-lg text-white text-sm placeholder-neutral-600 focus:outline-none focus:border-[#C9A961] transition-colors"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword((v) => !v)}
                      className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-neutral-500 hover:text-neutral-300"
                      aria-label={
                        showPassword ? "Hide password" : "Show password"
                      }
                    >
                      {showPassword ? (
                        <EyeOff className="w-4 h-4" />
                      ) : (
                        <Eye className="w-4 h-4" />
                      )}
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-xs text-neutral-500 mb-1.5 uppercase tracking-wide">
                    Confirm Password
                  </label>
                  <div className="relative">
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-500" />
                    <input
                      type={showPassword ? "text" : "password"}
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      required
                      placeholder="Re-enter password"
                      className="w-full pl-11 pr-4 py-2.5 bg-neutral-900 border border-neutral-800 rounded-lg text-white text-sm placeholder-neutral-600 focus:outline-none focus:border-[#C9A961] transition-colors"
                    />
                  </div>
                </div>

                {error && (
                  <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-xs">
                    {error}
                  </div>
                )}

                <button
                  type="submit"
                  disabled={submitting}
                  className="w-full py-3 bg-[#C9A961] text-black font-medium rounded-lg hover:bg-[#C9A961]/90 transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {submitting ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Updating…
                    </>
                  ) : (
                    "Update Password"
                  )}
                </button>
              </form>
            </>
          ) : (
            // ===== Success state =====
            // Brief celebration, then auto-redirect home. User can also
            // click through if they're impatient.
            <div className="text-center py-2">
              <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-green-500/10 border border-green-500/30 mb-5">
                <CheckCircle className="w-7 h-7 text-green-400" />
              </div>
              <h2 className="text-xl font-medium text-white mb-2">
                Password updated
              </h2>
              <p className="text-sm text-neutral-400 leading-relaxed mb-6">
                You can now sign in with your new password. Redirecting you to
                the sign-in page…
              </p>
              <Link
                href="/"
                className="inline-block w-full py-2.5 bg-neutral-900 border border-neutral-700 rounded-lg text-neutral-300 text-sm hover:border-neutral-600 transition-colors"
              >
                Continue to Sign In
              </Link>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// Default export — Suspense wrapper. The fallback matches the page's
// own dark theme so the transition is invisible to the user; in
// practice this flashes for a single frame at most.
export default function ResetPasswordPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-luxury-black flex items-center justify-center">
          <Loader2 className="w-8 h-8 text-luxury-gold animate-spin" />
        </div>
      }
    >
      <ResetPasswordPageInner />
    </Suspense>
  );
}
